# Generated by Django 2.1.1 on 2018-10-24 17:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_visible', models.BooleanField(null=True)),
                ('activation_key', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('slogan', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reddit', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter', models.CharField(blank=True, max_length=30, null=True)),
                ('youtube', models.CharField(blank=True, max_length=30, null=True)),
                ('linkdin', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
