# Generated by Django 2.1.1 on 2018-12-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_gallerymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
