# Generated by Django 2.1.1 on 2018-12-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181210_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
