# Generated by Django 2.1.1 on 2018-12-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181210_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryModel',
            new_name='Gallery',
        ),
    ]
