# Generated by Django 2.1.1 on 2018-12-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181210_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
