# Generated by Django 2.1.1 on 2018-12-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181210_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='img_1',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_2',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_3',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
