# Generated by Django 2.1.1 on 2018-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181211_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_4',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_5',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_6',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
