# Generated by Django 2.1.1 on 2018-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20181211_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_7',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_8',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_9',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
