# Generated by Django 2.1.1 on 2018-12-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20181211_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_img', models.ImageField(default='default.jpg', upload_to='images')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img_9',
        ),
        migrations.AddField(
            model_name='gallery',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
