# Generated by Django 2.1.1 on 2018-12-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20181214_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
