# Generated by Django 2.1.1 on 2018-12-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20181225_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='webpage',
        ),
    ]
