# Generated by Django 2.1.1 on 2019-01-23 14:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190110_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='extra_img',
            field=models.ImageField(default='default.jpg', upload_to=account.models.user_directory_path),
        ),
    ]
