# Generated by Django 2.1.1 on 2018-10-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactView',
        ),
    ]
