# Generated by Django 2.1.1 on 2018-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0002_delete_contactview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=40, null=True)),
                ('quote', models.TextField(default='n/a')),
                ('composer', models.CharField(blank=True, max_length=40, null=True)),
                ('daily_word', models.CharField(blank=True, max_length=40, null=True)),
                ('daily_def_1', models.TextField(default='n/a')),
                ('daily_def_2', models.TextField(default='n/a')),
                ('palabra_dia', models.CharField(blank=True, max_length=40, null=True)),
                ('palabra_def_1', models.TextField(default='n/a')),
                ('palabra_def_2', models.TextField(default='n/a')),
                ('temp', models.CharField(blank=True, max_length=40, null=True)),
                ('humidity', models.CharField(blank=True, max_length=40, null=True)),
                ('wind', models.CharField(blank=True, max_length=40, null=True)),
                ('pressure', models.CharField(blank=True, max_length=40, null=True)),
                ('sunup', models.CharField(blank=True, max_length=40, null=True)),
                ('sundown', models.CharField(blank=True, max_length=40, null=True)),
                ('day_length', models.CharField(blank=True, max_length=40, null=True)),
                ('in_decrease', models.CharField(blank=True, max_length=40, null=True)),
                ('moonup', models.CharField(blank=True, max_length=40, null=True)),
                ('moondown', models.CharField(blank=True, max_length=40, null=True)),
                ('forecast', models.TextField(default='n/a')),
                ('dollars', models.CharField(blank=True, max_length=40, null=True)),
                ('euros', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
