# Generated by Django 2.1.1 on 2019-02-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_scrapemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapemodel',
            name='day_length',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='in_decrease',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='moondown',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='moonup',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='sundown',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='sunup',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='scrapemodel',
            name='wind',
        ),
    ]
