# Generated by Django 2.1.1 on 2023-10-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20190217_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeModel',
        ),
    ]
